# Netlify Configuration for BunnySpaces Demo

[build]
  # Build command (not needed for static HTML)
  command = ""
  # Directory to publish (root directory)
  publish = "."

[build.environment]
  # Node.js version for any build processes
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"
    
    # CORS headers for fonts and assets
    Access-Control-Allow-Origin = "*"

# Specific caching for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Optimize CSS and JS caching
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# 404 handling (optional - fallback to main page)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain configuration
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

# Form handling (if needed in future)
[forms]
  settings = true